version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: sifen_user
      POSTGRES_PASSWORD: sifen_password
      POSTGRES_DB: sifen_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
